"""change quantity type

Revision ID: 21a22417f464
Revises: 5857822d1d68
Create Date: 2026-05-16 09:55:10.144527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a22417f464'
down_revision: Union[str, Sequence[str], None] = '5857822d1d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=3),
               existing_nullable=False)
    # ### end Alembic commands ###
